### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by Helias** [wowserhq/client#66]
I tested this repository quickly following the README, but I only got this

![image](https://github.com/user-attachments/assets/e8f0ac42-6cd7-46e0-9e96-8e108842abb3)

Are there any features already implemented on this client?

**Comment by timkurvers** [comment]
The status from the README is relatively accurate:

> This repository contains the Wowser web client, which currently has support for:
>
> - Loading Blizzard UI files (.toc, .xml and .lua)
> - Extremely primitive scene rendering using WebGL 2 (frames and textures mostly)
> - GLSL ES 300 shaders and PNG textures (no BLP support yet)

To select which UI is rendered, uncomment the relevant line in `index.ts`:

```ts
await client.ui.load('Wowser\\Wowser.toc');
// await client.ui.load('Interface\\GlueXML\\GlueXML.toc'); // login UI
// await client.ui.load('Interface\\FrameXML\\FrameXML.toc'); // in-game UI
```

No 3D scene rendering is implemented yet (see `wowserhq/wowser` for that).

**Comment by Helias** [comment]
I will try to comment these lines of codes, by the way I tried to run wowserhq/wowser but I encountered some issues during the installation, I could open a separate issue if you want.

**Comment by timkurvers** [comment]
> I tried to run wowserhq/wowser but I encountered some issues during the installation, I could open a separate issue if you want.

Yeah, `wowserhq/wowser` is effectively old and unmaintained at this point, and as such is notoriously hard to get up and running on newer Node.js and/or OS versions (in particular Apple Silicon is a pain in the behind).
